# 2021년 코딩 노트

## 220124_k-mooc 스터디

In [2]:
import numpy as np

In [3]:
  a1 = np.random.rand(4)
  a2 = np.random.rand(4, 1)
  a3 = np.array([[1, 2, 3, 4]])
  a4 = np.arange(1, 4, 1)
  a5 = np.linspace(1 ,4, 4)  

In [4]:
a1

array([0.14855799, 0.21841393, 0.8847023 , 0.09306459])

In [5]:
a2

array([[0.56493788],
       [0.33489155],
       [0.13504183],
       [0.92303762]])

In [6]:
a3

array([[1, 2, 3, 4]])

In [7]:
a4

array([1, 2, 3])

In [8]:
a5

array([1., 2., 3., 4.])

In [10]:
a5.shape == a1.shape

True

In [11]:
  import re 
  s = 'ACBCAC' 

In [16]:
  import re
  s = 'ACAABAACAAAAB'
  result = re.findall('A{1,2}', s)
  L = len(result)  

In [17]:
L

5

In [20]:
def l2_dist(a, b): 
  result = ((a - b) * (a - b)).sum() 
  result = result ** 0.5 
  return result  

In [22]:
l2_dist(a.T, b.T)

NameError: name 'a' is not defined

## 211217_방학중 코딩 프로젝트 마인드 스톰
- 브라이틱스 
- 인구그래프 업그레이드
- 머신러닝 : 혼자공부하는 머신러닝

# 211210_코딩꺼리
### 텔레그램봇 유지보수
- 에러메세지 보이지 않게 하기
    - 조건문을 걸어서 에러메세지가 뜨면 다시 코드 실행하기

# 211210_프로그램을 빠르게 작동하는 방법
- 컴퓨터가 잘 받아들이는 숫자로 변환하기
    - 용호교장님과의 대화에서 엑셀프로그램을 획기적으로 빠르게 작동시킨 팁

# 211208_다이얼로그 플로(dialogflow)
## 211208_다이얼로그 플로의 재발견
- webhook 서버(파이선 플라스크)를 구축
- 다이얼로그와 연계하기
- uipath와 연동하여 작업수행하기
    -  학술지 : 다이얼로그플로 + UIPath 연동하여 항공권예매하기 구현

# 211207_한글 프로그램 연수
## 211207_메일머지 라벨의 활용
- 한페이지에 여러개의 내용을 이용할때는 라벨 이요하기
- 기존의 메일머지와 차이점
    - 메일머지 : 상장처럼 한페이지에서 이름과 반번호가 바뀔때 사용
    - 라벨 : 이름표와 같이 한페이지에 여러개의 칸이 있는 경우 사용

# 211129_텔레그램봇 국내주식 수집 기능 추가
### 211206_순차적 코딩 시도
- 라즈베리파이에서 에러 발생
- 맥에서 다시 시도하기 

### 211203_국내주식 가격 크롤링
- yfinance 라이브러리 활용

### 211130_작업내용
- 미국주식 코드에 종목만 바꿔서 넣음.
    - 미국 주식코드는 정상작동
    - 한국 주식 코드 입력
        - 에러메세지 출력 : Error message: list index out of range
- 원인분석
    - 클래스 코드에서는 따로 건드릴 내용이 없음.
    - 기존코드도 건드릴 내용이 없음. 미국 종목은 정상출력됨. 
        - 왜? 한국종목만 제대로 출력되지 않을까?
        - 출력시 메세지기 다를까?

### 211129_추진내용
- stck
- 수집 코드
    - 삼성전자, 카카오, 카카오뱅크, 네이버, 카카오게임즈

### 211129_진행상황
- 에러메세지 발생
    - IndexError: list index out of range

# 211206_TIL
- 오피스 강의 듣기
- 한글프로그램 공부할것
    - 개요작성, 스타일
    - 인사작업 문서 작성에도 적용가능할듯
- 구글스프레드 시트 
    - 반편성작업에서 통합 기능 적용
    - 각반별로 데이터 받고, 배열로 합치기
    - 배열로 받은 데이터를 쿼리로 데이터 뽑기

# 211205_TIL
## 독서 - 코스모스
- 1000억개의 은하, 1개 은하에 1000억개의 별, 1개의 별에 크고작은 행성들중 내가 살고 있는 지구
- 천문학을 배울수록 겸손해진다는 말씀이 이해되는 수치
- 지구가 선택받은 행성처럼 느껴지는 이유는 지구의 환경에 맞는 유기물들이 살아남아서 진화를 했기 때문
- 만약 우주 어딘가에 생명체가 있다면, 주변 환경에 맞게 진화하여 자기가 사는 곳이 선택받은 곳이라고 생각할 것.

## 코딩
- 코딩으로 우주를 탐구할 수 없을까?
- 국내주식 크롤링
    - 단계별 실행하기

# 211202_터미널로 cpu온도 알아내기
- 라즈베리파이에서 cpu 온도 알아내기
    - 설치하기
        - sudo apt install lm-snesors
    - 사용하기
        - sensors

# 211130_파이선 에러 잡기
- 출력메세지 : inconsistent use of tabs and spaces in indentation
    - 탭과 스페이스바의 혼재로 에러발새이
- 해결방법 : autopep8 설치후 프로그램 실행
    - 설치하기 : pip install --upgrade autopep8
    - 실행하기 : autopep8 -i myfile.py

## 211128_인공지능 챗본관련 학술지 수집
- 대학원 수업대비 자료수집
    - 인공지능 챗봇을 활용한 초등영어 말하기 지도의 전망 Dialogflow를 중심으로.pdf
    - Dialogflow를 이용한 음성 기반 대화형 서비스 구현.pdf
    - 학사업무 지원 챗봇 개발.pdf
    - 챗봇 제작을 통한 인공지능교육 체험.pdf
    - Google Dialogflow를 활용한 레시피 챗봇에 관한 연구.pdf
    - 메이커 교육 기반 인공지능 챗봇 수업 개발.pdf
    - RPA 툴과 Diaogflow를 활용한 Chatbot 서비스 개발.pdf
    - kyobo_10611610.pdf
    - 초등영어 예비교사들이 개발한 인공지능 챗봇.pdf
    - 학사 정보 기반 챗봇 시스템 설계 및 구현.pdf
    - 일상 대화를 주제로 하는 감성 대화가 가능한 인공지능 기반 챗봇.pdf
    - 인공지능을 활용한 영어 학습용 챗봇 시스템 개발 방안 연구.pdf
    - 인공지능 챗봇의 교육적 활용 연구 동향 분석 활동이론을 중심으로.pdf
    - 챗봇_기반_인공지능_교육_프.pdf
    - 인공지능 챗봇을 활용한 웹 기반 코딩학습 지원도구 프로토타입 개발.pdf
    - kyobo_10540702.pdf
    - 인공지능기반챗봇서비스를활용한와인추천앱개발.pdf

## 211126_인구그래프 프로그램 재시작
### 기록의 이유
- 서버 재부팅으로 플라스크 앱 기동방법을 잊음.

### 프로그램 재시작 방법
- screen 프로그램으로 2개의 스크린 만들기
    - screen -S population   # 플라스크 앱 작동시킬 스크린
    - screen -S fsk_ingu_graph  # ngrok 외부 프로그램 작동 스크린
        
    
- 플라스크 앱 시작
    - python server.py  # 파이선을 이용해서 서버파일 실행
        - 192.168.10.115:8002
        
- ngrok를 이용한 외부에서 앱 접속 하기
    -  cd ~ 홈화면으로 이동
    - ./ngrok http 8002  # 8002번포트를 이용해서 외부에서 접속하기
    
### 할일
- 인구데이터 받기 오류
- 시군별 데이터 받기가 안됨.

## 211119_인구그래프 유지보수

- 인구그래프 플라스크 서버 실행하기
    - export FLASK_APP = server.py # 플라스크로 실행시킬 파일명을 설정
- 서버실행 되지 않음.
    - 가상환경 생성
        - pyenv virtualenv app_population
    - 인구그래프 폴더를 가상환경으로 지정
        - pyenv local app_population
    - 라이브러리 설치
    - flask
    - pandas
    - matplotlib
- ngrok 서비스 이용해서 외부에서 접속 가능하도록 설정

## 211124_관련 패키지 삭제하는 방법

- 관련 패키지 확인
    - pip show [패키지 이름]
    - pip show pdftopptx
- 관련 패키지 복사하여 텍스트파일에 저장
    - vim pkg.txt
    - 패키지 저장하기
- 관련 패키지 일괄 삭제
    - pip uninstall -y -r pkg.txt