<a href="https://colab.research.google.com/github/951237/TIL/blob/master/200818_TIL_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%ED%92%88%EC%A2%85%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 코딩야학 - 텐서플로 아이리스 품종 분류

## 0. 라이브러리 호출 및 변수 선언선언

In [1]:
import tensorflow as tf
import pandas as pd

URL = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'

## 1. 과거의 데이터 준비준비

In [ ]:
iris = pd.read_csv(URL)
iris

In [ ]:
iris = pd.get_dummies(iris) # 원핫 인코딩 - 분류값을 수치화 시켜줌.

In [21]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   꽃잎길이           150 non-null    float64
 1   꽃잎폭            150 non-null    float64
 2   꽃받침길이          150 non-null    float64
 3   꽃받침폭           150 non-null    float64
 4   품종_setosa      150 non-null    uint8  
 5   품종_versicolor  150 non-null    uint8  
 6   품종_virginica   150 non-null    uint8  
dtypes: float64(4), uint8(3)
memory usage: 5.3 KB


In [4]:
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [28]:
i_val = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']] # 독립변수 / 독립변수 만들때 데이터프레임 붙여주기
d_val = iris[['품종_setosa', '품종_versicolor', '품종_virginica']] # 종속변수 / 종속변수 만들때 데이터 프레임 붙여주기

## 2. 모델의 구조 만들기

In [23]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics = 'accuracy')

## 3. 데이터로 모델 학습(FIT)

In [ ]:
model.fit(i_val, d_val, epochs=1000)

## 4. 모델이용하기

In [27]:
print("예측하기 : ", model.predict(i_val[0:5])) # 예측 데이터는 독립변수에서 가져다 쓰기

예측하기 :  [[9.9913579e-01 8.6428539e-04 5.1399343e-08]
 [9.9644381e-01 3.5557006e-03 4.4359976e-07]
 [9.9837118e-01 1.6285523e-03 1.8155747e-07]
 [9.9538332e-01 4.6158275e-03 8.4581143e-07]
 [9.9929857e-01 7.0137350e-04 4.2282398e-08]]
